packages:
  - 'apps/*'
  - 'packages/*'
  - 'tooling/*'

catalog:
  # Core React 19 + Next.js 15 stack
  next: "^15.2.0"
  react: "^19.0.0"
  react-dom: "^19.0.0"

  # TypeScript ecosystem
  typescript: "~5.6.0"
  "@types/react": "^19.0.0"
  "@types/react-dom": "^19.0.0"

  # Radix UI - Pin versions for stability
  "@radix-ui/react-dialog": "^1.1.2"
  "@radix-ui/react-dropdown-menu": "^2.1.2"
  "@radix-ui/react-tooltip": "^1.1.3"
  "@radix-ui/react-select": "^2.1.2"

  # Tailwind CSS v4 (new)
  tailwindcss: "^4.0.0"
  "@tailwindcss/postcss": "^4.0.0"

  # Development dependencies
  eslint: "^9.0.0"
  prettier: "^3.0.0"
  turbo: "^2.0.0"

packageExtensions:
  # Handle React 19 peer dependency conflicts
  "*":
    peerDependenciesMeta:
      react:
        optional: false # Or true if you want to allow older React versions in some packages
      react-dom:
        optional: false # Or true
