packages:
  # All app directories
  - 'apps/*'
  # All package directories
  - 'packages/*'
  # All tooling directories
  - 'tooling/*'
  # Exclude build artifacts and dependencies
  - '!**/node_modules'
  - '!**/.next'
  - '!**/dist'
  - '!**/build'