rules:
  medical:
    type: attribute
    path: "member.coverageTypes.some(c => c.productType === 'M')"
    description: "Checks if the member has any medical coverage."
  dental:
    type: attribute
    path: "member.coverageTypes.some(c => c.productType === 'D')"
    description: "Checks if the member has any dental coverage."
  vision:
    type: attribute
    path: "member.coverageTypes.some(c => c.productType === 'V')"
    description: "Checks if the member has any vision coverage. (Example)"
  loyaltyProgram:
    type: computed
    expr: "userInfo.roles.includes('LOYA')"
    description: "Checks if the user is part of the loyalty program based on roles."
  premiumHealth:
    type: static
    value: true
    description: "Static flag, e.g., for a feature always enabled in this local setup."
  canViewClaims:
    type: authFunction
    name: "VIEW_CLAIMS"
    description: "Checks if the user has the VIEW_CLAIMS auth function available."
  isTestUser:
    type: lob # Example: Using LOB to identify test users
    values: ["TEST_LOB"]
    description: "Checks if the user belongs to a specific Line of Business designated for testing." 